name: myenv
channels:
  - conda-forge
dependencies:
  - pip
  - scikit-surprise=1.1.14
  - pip:
      - numpy=1.26.4
      - pandas=2.2.2
      - contractions=0.1.73
      - scikit-learn=1.5.1
      - joblib=1.4.2
      
