name: myenv
channels:
  - conda-forge
dependencies:
  - pip
  - scikit-surprise
  - pip:
      - numpy
      - pandas
      - nltk
      - contractions
      - scikit-learn
      - joblib
      - streamlit
      
