name: myenv
channels:
  - conda-forge
dependencies:
  - pip
  - scikit-surprise
  - pip:
      - numpy<=2.2.0
      - cython
      - pandas
      - scipy
      - contractions
      - scikit-learn
      - nltk
      - joblib
      - streamlit
